// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJCzPtHQvpBFej-EmQPs7EeF6Ea3agkVc',
    appId: '1:154344098245:web:97a3cb77f4ec34e02fe3ac',
    messagingSenderId: '154344098245',
    projectId: 'cropdoc-6b3ab',
    authDomain: 'cropdoc-6b3ab.firebaseapp.com',
    storageBucket: 'cropdoc-6b3ab.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXfIlndr6cTmEO-p8yTU2ZcumqJl_LrgA',
    appId: '1:154344098245:android:694aff80c9134d512fe3ac',
    messagingSenderId: '154344098245',
    projectId: 'cropdoc-6b3ab',
    storageBucket: 'cropdoc-6b3ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArF-lqSTt822DHRxskaIEUWyXGnt0zKxE',
    appId: '1:154344098245:ios:3c506079b7da41dd2fe3ac',
    messagingSenderId: '154344098245',
    projectId: 'cropdoc-6b3ab',
    storageBucket: 'cropdoc-6b3ab.firebasestorage.app',
    androidClientId: '154344098245-1b3fo44qki83tjhatu8jo1uneu3hk7jj.apps.googleusercontent.com',
    iosClientId: '154344098245-qv7pl8dr8hklfd7iett43db54pbnq3nd.apps.googleusercontent.com',
    iosBundleId: 'com.example.cropsafeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArF-lqSTt822DHRxskaIEUWyXGnt0zKxE',
    appId: '1:154344098245:ios:3c506079b7da41dd2fe3ac',
    messagingSenderId: '154344098245',
    projectId: 'cropdoc-6b3ab',
    storageBucket: 'cropdoc-6b3ab.firebasestorage.app',
    androidClientId: '154344098245-1b3fo44qki83tjhatu8jo1uneu3hk7jj.apps.googleusercontent.com',
    iosClientId: '154344098245-qv7pl8dr8hklfd7iett43db54pbnq3nd.apps.googleusercontent.com',
    iosBundleId: 'com.example.cropsafeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJCzPtHQvpBFej-EmQPs7EeF6Ea3agkVc',
    appId: '1:154344098245:web:3c84f0f781ff73ca2fe3ac',
    messagingSenderId: '154344098245',
    projectId: 'cropdoc-6b3ab',
    authDomain: 'cropdoc-6b3ab.firebaseapp.com',
    storageBucket: 'cropdoc-6b3ab.firebasestorage.app',
  );
}
